### PR TITLE
Add suggestions

### PR DESCRIPTION
**Pull request by markbreedlove**
This PR adds a search suggestions endpoint, which receives a string and returns a list of alternatives for a couple of chosen fields based on what those fields contain that's similar.

The new endpoint is `/v2/suggestion`. It takes the usual `api_key` parameter, plus `text`, for the text to consider.

@mgiraldo Don't worry too much about the code review, but can you tell me if the structure of the results is something that you think will be useful for the frontend? I have the results broken down by field: a separate list of alternatives for each field in our schema. That's how Elasticsearch wants to return the suggestions, and it seems like it's useful to keep things separated by field and leave it up to the user-agent (e.g. the frontend) to decide how to use the information.  (I'll let you know where you can access a demo.)

### CODE REVIEW

**Comment by mgiraldo** [comment]
for `text=russian+ballet` i get:

image

is it that the user-provided input always comes last? are there no words suggested for “ballet”?

**Comment by markbreedlove** [comment]
If `ballet` is already an exact match for a token that exists in the index you won't get it as a suggestion. Have you spotted any term that's similar to `ballet` but not exactly? (For example, I do `text=ballet` and get nothing back because it's good as-is.)

**Comment by markbreedlove** [comment]
Regarding the ordering, it's sorted by Elasticsearch's default -- the computed score of the term. There are many factors involved, having to do with frequency in the index and within documents themselves. Sometimes it comes first or higher on the list; depends on the search.

**Comment by mgiraldo** [comment]
for `text=world+war+i+poster`

image

it would be necessary to get some more insight of the criteria ES has for returning the list... are these words things that have results in ES, maybe more results than the provided text?

**Comment by markbreedlove** [comment]
To get real insight into Elasticsearch, I'd have to refer you to the Elasticsearch documentation, because it's more than I can get into here and honestly it's hard to understand, but I've done my best to get it to produce useful results. These are all terms that have results, so to speak -- they are tokens that Elasticsearch has encountered; and the scoring is complicated, but it is relevant to the frequency of occurrences.

If you spend time with it, across a number of queries, do you find that the results are not useful?

**Comment by mgiraldo** [comment]
i guess i want to know elastic's definition of suggestion. but i guess i can read the manual. do you have a link for that or should i start at elastic.co?

**Pull request closed without merging**
